export const Freelances = [
	{
		id: '1',
		name: 'Luis Villasmil',
		job: 'Développeur mobile',
		picture: '../../assets/profils/luis-villasmil.jpg',
		skills: ['React Native'],
		location: 'Lyon',
		available: true,
		tjm: 500,
	},
	{
		id: '2',
		name: 'Etty Fidele',
		job: 'Développeuse fullstack',
		picture: '../../assets/profils/etty-fidele.jpg',
		skills: ['Node JS', 'Vue.js', 'React', 'AWS'],
		location: 'Paris',
		available: false,
		tjm: 620,
	},
	{
		id: '3',
		name: 'Kim Doan',
		job: 'Développeuse frontend',
		picture: '../../assets/profils/kimson-doan.jpg',
		skills: ['React', 'Gatsby', 'Next.js'],
		location: 'Bordeaux',
		available: true,
		tjm: 520,
	},
	{
		id: '4',
		name: 'Rachel Mc Dermott',
		job: 'Product Designer',
		picture: '../../assets/profils/rachel-mcdermott.jpg',
		skills: ['Figma', 'Webflow'],
		location: 'Lille',
		available: false,
		tjm: 650,
	},
	{
		id: '5',
		name: 'Sigmund Rolland',
		job: 'Développeur mobile',
		picture: '../../assets/profils/sigmund.jpg',
		skills: ['IOS', 'Android'],
		location: 'Lyon',
		available: false,
		tjm: 450,
	},
	{
		id: '6',
		name: 'Grégoire Ferreira',
		job: 'Développeur backend',
		picture: '../../assets/profils/wellington-ferreira.jpg',
		skills: ['Python', 'Django', 'Docker'],
		location: 'Paris',
		available: true,
		tjm: 510,
	},
	{
		id: '7',
		name: 'Joesef Key',
		job: 'Designer',
		picture: '../../assets/profils/joesef-key.jpg',
		skills: ['Sketch', 'Illustrator'],
		location: 'Paris',
		available: true,
		tjm: 480,
	},
	{
		id: '8',
		name: 'Hugo Vysa',
		job: 'Développeur frontend',
		picture: '../../assets/profils/alexander-hipp.jpg',
		skills: ['SEO', 'Javascript Vanilla'],
		location: 'Toulouse',
		available: false,
		tjm: 560,
	},
	{
		id: '9',
		name: 'Mina Toman',
		job: 'Développeuse Mobile',
		picture: '../../assets/profils/gabriel-silverio.jpg',
		skills: ['Android', 'React Native'],
		location: 'Bayonne',
		available: true,
		tjm: 630,
	},
	{
		id: '10',
		name: 'Amélie Nackos',
		job: 'Développeuse backend',
		picture: '../../assets/profils/jaky-nakos.jpg',
		skills: ['Node.js', 'Express', 'Docker'],
		location: 'Paris',
		available: false,
		tjm: 400,
	},
	{
		id: '11',
		name: 'Maxime Engelsen',
		job: 'Intégrateur SEO',
		picture: '../../assets/profils/ben-den-engelsen.jpg',
		skills: ['SEO'],
		location: 'Rennes',
		available: false,
		tjm: 600,
	},
]
